spring:
  application:
    name: zuul-gateway-consumer
server:
  port: 9091
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api:
      path: /**
      serviceId: ribbon-consumer
