spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/ohcomeyes/spring-cloud.git
          force-pull: true
          search-paths: config
  rabbitmq:
    host: 192.168.1.252
    port: 5672
    username: admin
    password: boce123456
      # username: ********
      # password: ********
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 关闭刷新安全认证
management:
  security:
    enabled: false